
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-29T13:11:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "54d749c01663235d1305dba2b9d04e379bb4b647",
 "version": "v0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
